apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/k8s/*
build:
    local:
        push: false
    # googleCloudBuild:
    #     projectId: preemielove-dev-381621
    artifacts:
        - image: zubairabubakar/preciouspreemie-auth #image: us.gcr.io/preemielove-dev-381621/auth
          context: auth
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        - image: zubairabubakar/preciouspreemie-client #image: us.gcr.io/preemielove-dev-381621/client
          context: client
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: '**/*.ts'
                    dest: .
                  - src: '**/*.tsx'
                    dest: .
        - image: zubairabubakar/preciouspreemie-products #image: us.gcr.io/preemielove-dev-381621/products
          context: products
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        - image: zubairabubakar/preciouspreemie-orders
          context: orders
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        - image: zubairabubakar/preciouspreemie-expiration
          context: expiration
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        - image: zubairabubakar/preciouspreemie-payments
          context: payments
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
