apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/k8s/*
build:
    # local:
    #     push: false
    googleCloudBuild:
        projectId: preemielove-dev-381621
    artifacts:
        - image: us.gcr.io/preemielove-dev-381621/auth
          context: auth
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
