name: deploy-products

on:
    push:
        branches:
            - main
        paths:
            - 'products/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd products && docker build -t zubairabubakar/preciouspreemie-products .
            - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            - run: docker push zubairabubakar/preciouspreemie-products
            - uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            - run: doctl kubernetes cluster kubeconfig save preciouspreemie-microservice
            - run: kubectl rollout restart deployment products-depl
